### ISSUE TITLE
Can I change the default port?

### ISSUE THREAD

**Issue by lotc** [serjs/socks5-server#1]
Hi there,
I would like to change the outbound port from `1080` to other (like 1234 as sample here).
Should I change the `-p 1080:1080` into `-p 1234:1234` ? Or do I need to make some changes on `Dockerfile` ?
Thanks!

**Comment by byumov** [comment]
@lotc , just run:
`docker run -d --name my-proxy -p 1234:1080 -e PROXY_USER=username -e PROXY_PASSWORD=password serjs/go-socks5-proxy`
where 1234 is outbound port.

**Comment by lotc** [comment]
Thanks for the answer.
