### ISSUE TITLE
curl example invalid

### ISSUE THREAD

**Issue by IlyaSemenov** [serjs/socks5-server#10]
curl example doesn't work with curl 7.54.0:

https://github.com/serjs/socks5-server/blob/2d33041af0d1309ea1c939291e488b39180e3097/README.md#L27

```
❯ curl --socks5 --user user:pass myhost.com:1111 http://ifcfg.co
curl: (3) Port number ended with 'b'
curl: (6) Could not resolve host: --user
curl: (6) Could not resolve host: --user
```

it should rather be:

```
❯ curl --socks5 user:pass@myhost.com:1111 http://ifcfg.co
111.222.333.444
```

**Comment by serjs** [comment]
Thank you for your comment, sorry for delay in action. I missed all notifications due misconfigured email filters for personal GitHub account🤦‍♂
