### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by JayNewstrom** [serjs/socks5-server#14]
Looks like you've been working on multi arch support. 
https://github.com/serjs/socks5-server/blob/master/hooks/build#L3

I'm looking to use this as on arm. Is there anything I can do to help you finish up support?

**Comment by serjs** [comment]
Hi!

I'm open to from other engineers ideas and samples of how to organize multiarch using current dockerhub CI integration.

Also I'm interested to make buildx builds for newer docker engine versions (after out from experimental stage https://docs.docker.com/buildx/working-with-buildx/)

**Comment by JayNewstrom** [comment]
I'm using buildx on another project, and it's working out quite well, I'm using github actions to build rather than dockerhub though. 

If there's a direction you'd like to go, I'd be happy to contribute.

**Comment by serjs** [comment]
Hi!

Yesterday I move from dockerhub CI to GitHub Actions with builds support, starting from v0.0.2 and latest docker image tags there are arm/amd64 images available

**Comment by JayNewstrom** [comment]
Awesome! Thanks!
