### ISSUE TITLE
Can't connect from Mac OS and iOS

### ISSUE THREAD

**Issue by DimaDDM** [serjs/socks5-server#29]
Got error like this, when try connect from iOS (iPhone)
<img width="660" alt="Screen Shot 2022-03-27 at 19 29 29" src="https://user-images.githubusercontent.com/4531719/160291210-42376bd3-aab4-4ca5-9331-0068e5193da2.png">

From Mac OS

<img width="690" alt="Screen Shot 2022-03-27 at 19 31 23" src="https://user-images.githubusercontent.com/4531719/160291273-9fd94bb0-b889-41cb-8e74-599649c1bbcf.png">

But curl test work fine

**Comment by serjs** [comment]
Hi! Can you show you network settings (or browser settings) with socks configuration? And server settings? (whithout private data) I can test Mac OS settings on some days, currently withot laptop.

**Comment by DimaDDM** [comment]
<img width="664" alt="Screen Shot 2022-04-02 at 12 12 48" src="https://user-images.githubusercontent.com/4531719/161376332-6521cf16-747f-49f1-9777-b90eea7e9f49.png">
I'm just using system settings on default configuration with custom port. Same on iPhone (wifi -> proxy with autorization)

**Comment by DimaDDM** [comment]
HTTP/HTTPS option also don't work. Work only curl test
