### ISSUE TITLE
PROXY_PORT env

### ISSUE THREAD

**Issue by shtirlic** [serjs/socks5-server#3]
It's nice to have port configurable

**Comment by ilnuribat** [comment]
Can you use 
```
-p <your_port>:1080
```
?

**Comment by shtirlic** [comment]
Yeah that's how I do it now, but ENV_PORT  would be great

**Comment by serjs** [comment]
Hi!

@shtirlic Today's :latest tag for image on dockerhub updated with PROXY_PORT, I merge changes into master and update README with all supported ENV params.

So you can change listen port for server.go in container or binary itself.

**Comment by serjs** [comment]
From v0.0.2 release already added this feature, so there are no need to use only latest image tag
So long without any updates
