### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by keunes** [serjs/socks5-server#34]
Hello,

I've started the container on my Raspberry Pi:
`docker run -d --name socks5 -p 8888:8888 -e PROXY_USER=keunes -e PROXY_PASSWORD=[password] serjs/go-socks5-proxy` and confirm that it's running:
```
CONTAINER ID   IMAGE                   COMMAND     CREATED          STATUS          PORTS                                       NAMES
babf826ab2cd   serjs/go-socks5-proxy   "/socks5"   45 minutes ago   Up 45 minutes   0.0.0.0:8888->8888/tcp, :::8888->8888/tcp   socks5
```
On my router I have opened the port, redirecting to my RaspberryPi (protocol: TCP):
![afbeelding](https://user-images.githubusercontent.com/11229646/200165796-c851063e-3606-4e58-ac07-d12bba10e9aa.png)

However, when testing, I get a 'connection refused' error:
```
$ curl --socks5 xxx.x.xx.xx:8888 -U keunes:[password] http://ifcfg.co
curl: (7) Failed to connect to 185.6.51.97 port 8888: Connection refused
```
I'm also running a 'bare' nginx server on the RasPi but I think it shouldn't interfere as it's on [another level](https://stackoverflow.com/a/11234800). I've also set up UFW on the RasPi but I tried adding a rule to open port `8888` and that didn't help, and I think it shouldn't interfere anyway as docker [manipulates iptables directly](https://www.linode.com/docs/guides/configure-firewall-with-ufw/).

Any hints/ideas?

**Comment by serjs** [comment]
Hi!

Server listen 1080 port [by default](https://github.com/serjs/socks5-server#list-of-all-supported-config-parameters). You need to specify `PROXY_PORT` environment variable or make docker port listener like 8888 -> 1080 in (host -> container) scheme.

**Comment by keunes** [comment]
Thanks  a lot! New with docker so I didn't put the correct info in the run command. Without auth I now get it to work.
