### ISSUE TITLE
Issue with the last Docker image

### ISSUE THREAD

**Issue by omarmhaimdat** [serjs/socks5-server#35]
We had an issue with the last version of the docker images, the container keeps restarting with the following logs:

```exec /socks5: exec format error
exec /socks5: exec format error
exec /socks5: exec format error
exec /socks5: exec format error
exec /socks5: exec format error
exec /socks5: exec format error
exec /socks5: exec format error
exec /socks5: exec format error
exec /socks5: exec format error

**Comment by omarmhaimdat** [comment]
#36 This DockerFile seems to work just fine

**Comment by omarmhaimdat** [comment]
The issue occurred in amd64, though I don't know if other platforms are affected.

**Comment by serjs** [comment]
Yeah, my fault. Buildx overwrite pushed image with armv6, replaced arm64,amd64 arch. I pushed back previous CI, fix amd64, arm64 images. Try againt for latest tag.
BTW, I recomment to use versioned images.

Need to review CI for multi-arch, or remove armv6 from supported arch (Pi zero1, Pi B, etc) in future
