### ISSUE TITLE
exec /socks5: exec format error, Docker Image Defaulting to Armv6 on Amd64

### ISSUE THREAD

**Issue by Mist-Hunter** [serjs/socks5-server#37]
Thanks for the great image, I use this everyday!

This morning my [watchtower ](https://github.com/containrrr/watchtower) grabbed your image a few minutes after it was pushed and then crashed. 

```
WARNING: The requested image's platform (linux/arm/v6) does not match the detected host platform (linux/amd64) and no specific platform was requested
```

```
exec /socks5: exec format error
```

This is true even when pulling serjs/go-socks5-proxy:bb9c21e67556 (which I checked in case I was pulling the wrong image somehow). Rolling back to serjs/go-socks5-proxy:v0.0.3 resolves.

**Comment by serjs** [comment]
Hi! Fixed due [this ](https://github.com/serjs/socks5-server/issues/35) report.
Still need to remake CI/CD based on binary distro changes for armv6, but amd64,arm64,armv7 is ok now.
