### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by ViktorBarzin** [serjs/socks5-server#5]
Is https supported? Cannot find a way to set it up...

**Comment by nima7r** [comment]
+

**Comment by serjs** [comment]
Hi! This repo and app supports only socks5 proxy, I have no plans to realize https support due this repo and codebase, and I have no plans of making https based proxy service based on this codebase.

As far as I see, there are some implementations for http/https protocol based proxy - https://github.com/elazarl/goproxy

Take a look at https://github.com/snail007/goproxy maybe it's more complicated and featured solution for your requirements
