### ISSUE TITLE
User / Pass not woring

### ISSUE THREAD

**Issue by Berndinox** [serjs/socks5-server#6]
`docker run -d --name socks5 -p 443:443 -e PROXY_USER=test -e PROXY_PASSWORD=1234 -e PROXY_PORT=443 serjs/go-socks5-proxy`

Tried some different Chrome Plugins:
- Proxy Helper
- FoxyProxy

always:
`2018/09/22 10:53:41 [ERR] socks: Failed to authenticate: No supported authentication mechanism`

**Comment by serjs** [comment]
Hi!

Looks like chrome doesn't support SOCKS5 authentication
There are some related issues on Proxy Helper issue tracker, digging through it you can find more info.
https://github.com/henices/Chrome-proxy-helper/issues/2

I try FoxyProxy in chrome and firefox. FF is fine, but chrome still have a problems. Can you confirm working SOCKS5 Auth in chrome at all? Try to use 3rd party socks5 proxy services with required auth.

Be aware of SOCKS5 auth glitches, when no required auth (and filled user:pass) works fine.
